### ISSUE TITLE
Do you think to add a fancy animation instead of refreshing? #Enhacement

### ISSUE THREAD

**Issue by Matias-Carazzo** [pavelk2/social-feed#172]
Im trying to add a fancy animation to add new post on the container.
Do you have any idea on how to implement it?

**Comment by tmlangley** [comment]
How about just using a css animation? 

Example:

``` css
.social-feed-container {
  overflow: hidden;
}

.social-feed-element {
  transform: translateY(800%);
  opacity: 0;
  transition: 1s top;

  animation: 1s ease-in-out slideup;
  animation-fill-mode: forwards;
}

@keyframes slideup {
  from {
    transform: translateY(800%);
    opacity: 0;
  }

  to {
    transform: translateY(0);
    opacity: 1;
  }
}
```
